# Generated by Django 5.2.11 on 2026-02-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Items',
        ),
    ]
