# Generated by Django 6.0.1 on 2026-02-28 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('event_type', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove'), ('ADJUST', 'Adjust')], default='ADJUST', max_length=10)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tracking.item')),
            ],
        ),
    ]
