# Generated by Django 6.0.2 on 2026-03-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_inventory_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='ItemsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('qty_after', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.items')),
            ],
        ),
    ]
