# Generated by Django 6.0.1 on 2026-03-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_itemledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemledger',
            name='event_type',
        ),
    ]
