# Generated by Django 6.0.2 on 2026-03-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_items_name_itemsledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
