# Generated by Django 6.0.2 on 2026-03-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_itemsledger_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsledger',
            name='qty_after',
        ),
    ]
